### ISSUE TITLE
 TypeError: Cannot read properties of undefined (reading 'func')

### ISSUE THREAD

**Issue by nasraldin** [Eomm/fastify-overview#98]
Hello team,

Please apply the fix to avoid the below issue that throw when using with typescript.

Current ver.
"fastify-overview": "3.7.0",
 "fastify": "4.26.0",

To reproduce the issue:
add the plugin
 ppm add fastify-overview

register to fastify 
import FastifyOverview from 'fastify-overview';
      fastify.register(FastifyOverview, {
        addSource: true, // current this opt is throw error and stoped the app start
        exposeRoute: true,
        exposeRouteOptions: {
          url: '/json-overview',
        },
      });

run your app

result 
application stoped to start and throw below error

Failed to start application: TypeError: Cannot read properties of undefined (reading 'func')
    at Boot.manInTheMiddle (/api/node_modules/.pnpm/fastify-overview@3.7.0/node_modules/fastify-overview/index.js:90:107)
    at Boot.markInstance (/api/node_modules/.pnpm/fastify-overview@3.7.0/node_modules/fastify-overview/index.js:30:20)
    at Boot.override (/api/node_modules/.pnpm/fastify@4.26.0/node_modules/fastify/lib/pluginOverride.js:69:56)
    at Plugin.exec (/api/node_modules/.pnpm/avvio@8.2.1/node_modules/avvio/plugin.js:79:33)
    at Boot.loadPlugin (/api/node_modules/.pnpm/avvio@8.2.1/node_modules/avvio/plugin.js:272:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

The fix:

In the manInTheMiddle function, update the check to ensure that _current has a value before assigning it to the source.

old fun is 
if (opts.addSource && this) {
    trackStructure.source = this._current.find(loadPipe => loadPipe.func[kSourceRegister] !== undefined).func[kSourceRegister]
}

new code 
if (opts.addSource && this) {
  const currentSourcePipe = this._current.find(loadPipe => loadPipe.func[kSourceRegister] !== undefined);
  if (currentSourcePipe) {
    trackStructure.source = currentSourcePipe.func[kSourceRegister];
  }
}

Thank you for creating such an amazing tool!

**Comment by matthyk** [comment]
You forgot to `await` the register of `fastifyOverview`. See in the docs:
https://github.com/Eomm/fastify-overview/blob/17fd92644283c5e2c538acb045088cf247b83507/README.md?plain=1#L50-L58

**Comment by nasraldin** [comment]
Hell @matthyk ,

I have reviewed the documentation and observed your note for await, but it does not seem to be the source of the problem. Please examine the snippet of code below, which utilizes the await.

```
const defaultOpts = {
      addSource: true, // current this opt is throw error and stoped the app startup
      exposeRoute: true,
      exposeRouteOptions: {
        url: '/json-overview',
      },
};

fastify.log.info('Fastify overview tree structure plugin enabled.');

await fastify.register(FastifyOverview, { ...defaultOpts });

fastify.log.info('The route is exposed at GET /json-overview');
```

**Comment by matthyk** [comment]
I don't get an error with the provided code snippet. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by Eomm** [comment]
> Please apply the fix to avoid the below issue that throw when using with typescript.

I don't define me as TS dev so I need something where I can just run these commands to replicate the error:

```
git clone xyz
npm install
npm start
```

TBH If that item is undefined, it means that the `getSource` util does not return anything:

https://github.com/Eomm/fastify-overview/blob/17fd92644283c5e2c538acb045088cf247b83507/index.js#L123

So, I think the issue relies on how the function returns the source and it is definitely not tested in this setup.

https://github.com/Eomm/fastify-overview/blob/17fd92644283c5e2c538acb045088cf247b83507/lib/source-code.js#L5

**Comment by nasraldin** [comment]
I have created one test app so you can run the check the issue
jus clone and install node modules then run dev command

https://github.com/nasraldin/test-fastify-overview

**Comment by matthyk** [comment]
@nasraldin @Eomm 

I now had the time to take a closer look at the problem and I have found the cause. The cause of this error is the `wrapRegister` method when using ECMAScript modules. See the code snippet below.
https://github.com/Eomm/fastify-overview/blob/c1785f8814a868071be1e474306e50185035e070/index.js#L120-L126

The `wrapRegister` function expects a plugin function (the `pluginFn` parameter) but depending on how the register method was called, the pluginFn has a different value. Below some example `register` calls and the corresponding value of the `pluginFn` parameter.

1.
```js
import Fastify from 'fastify'
import fastifyOverview from 'fastify-overview'
import plugin from './plugin.js'

const app = Fastify()
await app.register(fastifyOverview)

app.register(plugin)
```
--> `pluginFn` would be the (async) function imported from `plugin.js`

2.
```js
import Fastify from 'fastify'
import fastifyOverview from 'fastify-overview'

const app = Fastify()
await app.register(fastifyOverview)

app.register(import('./plugins.js'))
```
--> `pluginFn` would be a `Promise<{ default: pluginFn }>`

3.
```js
import Fastify from 'fastify'
import fastifyOverview from 'fastify-overview'

const app = Fastify()
await app.register(fastifyOverview)

app.register(await import('./plugins.js'))
```
--> `pluginFn` would be the same as the second but without the Promise so, `{ default: pluginFn }`


So the problem is that the plugin function can also be a Promise or a [Module Namespace Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#module_namespace_object). The Second point could be easily fixed with a simple check, like [Avvio does](https://github.com/fastify/avvio/blob/a153be8358ece6a1ed970d0bee2c28a8230175b9/boot.js#L162) with this [function](
https://github.com/fastify/avvio/blob/a153be8358ece6a1ed970d0bee2c28a8230175b9/lib/is-bundled-or-typescript-plugin.js#L13-L19). If the plugin is a Promise we would have to await it before we continue, but I can't tell if we can just make the method async.

See [here](https://github.com/matthyk/fastify-overview-issue-98) for minimal reproducible example.

**Comment by Eomm** [comment]
It seems we have an actionable! Great analysis!

> f the plugin is a Promise we would have to await it before we continue, but I can't tell if we can just make the method async.

This is dangerous because we are no more watching the actual runtime status, but we are doing business logic. In this case I would just try to get all the info we can and check where we could store them since the pluginFn seems not an option

**Comment by matthyk** [comment]
@Eomm 

While I was analysing the issue, I found another problem. If you run `npm run load` in my [example project](https://github.com/matthyk/fastify-overview-issue-98) you get the following overview output.

```json
{
  "id": 0.6509491979399917,
  "name": "fastify -> fastify-overview",
  "children": [
    {
      "id": 0.2302123930057709,
      "name": "default",
      "children": [],
      "routes": [],
      "decorators": {
        "decorate": [
          {
            "name": "num",
            "type": "number",
            "source": {
              "stackIndex": 0,
              "fileName": "file:///Users/.../fastify-overview-issue-98/plugin.js",
              "relativeFileName": "file:///plugin.js",
              "lineNumber": 2,
              "columnNumber": 9,
              "functionName": "default",
              "typeName": null,
              "methodName": null
            }
          }
        ],
        "decorateRequest": [],
        "decorateReply": []
      },
      "hooks": {
        "onRequest": [],
        "preParsing": [],
        "preValidation": [],
        "preHandler": [],
        "preSerialization": [],
        "onError": [],
        "onSend": [],
        "onResponse": [],
        "onTimeout": [],
        "onRequestAbort": [],
        "onListen": [],
        "onReady": [],
        "preClose": [],
        "onClose": [],
        "onRoute": [],
        "onRegister": []
      },
      "source": {
        "stackIndex": 0,
        "fileName": "node:internal/process/task_queues",
        "relativeFileName": "node:internal/process/task_queues",
        "lineNumber": 82,
        "columnNumber": 21,
        "functionName": "processTicksAndRejections",
        "typeName": "process",
        "methodName": null
      }
    }
  ],
  "routes": [],
  "decorators": {
    "decorate": [],
    "decorateRequest": [],
    "decorateReply": []
  },
  "hooks": {
    "onRequest": [],
    "preParsing": [],
    "preValidation": [],
    "preHandler": [],
    "preSerialization": [],
    "onError": [],
    "onSend": [],
    "onResponse": [],
    "onTimeout": [],
    "onRequestAbort": [],
    "onListen": [],
    "onReady": [],
    "preClose": [],
    "onClose": [],
    "onRoute": [],
    "onRegister": []
  }
}
```

While the source object of the `num` decorator is correct the source object of the plugin itself is not correct, since is contains `node:internal/process/task_queues` as `fileName`.

**Comment by matthyk** [comment]
I can no longer reproduce this output. it seems that I had some strange side effects 😄

**Comment by matthyk** [comment]
@Eomm I have opened #105 to discuss a possible solution. But if you look at the failed tests, you can also see another problem. As soon as you use ECMAScript modules, you no longer get the correct `fileName` in the source. See https://github.com/Eomm/fastify-overview/actions/runs/8103392570/job/22147905402?pr=105#step:5:74

**Comment by Eomm** [comment]
Thanks for taking care of this issue.

TBH I would check how APMs do it

**Comment by matthyk** [comment]
I've been looking for a solution for some time now, but haven't found one yet. But maybe we should solve the problem with the sources separately from the issues with the registration of ECMAScript modules, since the two things have nothing to do with each other.

**Comment by Eomm** [comment]
I did not understand: are you suggesting to add a condition to avoid the crash?

**Comment by matthyk** [comment]
Current situation: The plugin crashes if a Module Namespace Object or a Promise is registered

My suggestion:

- For Module Namespace Object: Check if the current plugin is a _Module Namespace Object_, and if so, register the corresponding function correctly
- For Promises: Let the plugin crash, since we currently do not have a solution but we could print a warning
